# Change these first
owner: quacks-yaks # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Jelly
    url: https://jelly.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
    __dangerous__body_degraded: '<title>Sign in ・ Cloudflare Access</title>'
  - name: Trans
    url: https://trans.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
    __dangerous__body_degraded: '<title>Sign in ・ Cloudflare Access</title>'
  - name: Pikvm
    url: https://pikvm.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
    __dangerous__body_degraded: '<title>Sign in ・ Cloudflare Access</title>'
  - name: Time
    url: https://time.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
    __dangerous__body_degraded: '<title>Sign in ・ Cloudflare Access</title>'
  - name: Files
    url: https://files.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
    __dangerous__body_degraded: '<title>Sign in ・ Cloudflare Access</title>'
assignees:
  - thisguycodes

status-website:
  cname: status.dis.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Time Status
  introTitle: "Service Status for Time"
  introMessage: "'degraded' indicates a problem with Cloudflare Access."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
workflowSchedule:
  responseTime: "0 * * * *"
  graphs: "20 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
