# Change these first
owner: quacks-yaks # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Jelly
    url: https://jelly.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
  - name: Trans
    url: https://trans.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
  - name: Pikvm
    url: https://pikvm.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
- name: Time
    url: https://time.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
- name: Files
    url: https://files.dis.dev
    headers:
      - "CF-Access-Client-Id: $CF_ID"
      - "CF-Access-Client-Secret: $CF_SECRET"
    expectedStatusCodes:
      - 200
assignees:
  - thisguycodes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dis.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
